Repository ErrorPirate/DWBH, pull requests merged in 2024-11, with the labels that each got.

#14 docs: readme 파일 1차 작성
  README.md
  frontend/src/images/Error-pirate.jpg
Labels: docs

#20 refactor: 스키마 리펙토링
  backend/src/main/resources/schema.sql
Labels: refactor

#23 feat: queryDSL 라이브러리 추가
  backend/build.gradle
  backend/src/main/java/com/dwbh/backend/config/QueryDslConfig.java
Labels: feat

#24 feat: 채팅방번호에 해당하는 평가 조회 기능 구현
  backend/src/main/java/com/dwbh/backend/config/QueryDslConfig.java
  backend/src/main/java/com/dwbh/backend/controller/evaluation/EvaluationController.java
  backend/src/main/java/com/dwbh/backend/dto/evaluation/EvaluationDTO.java
  backend/src/main/java/com/dwbh/backend/dto/evaluation/EvaluationResponse.java
  backend/src/main/java/com/dwbh/backend/entity/evaluation/Evaluation.java
  backend/src/main/java/com/dwbh/backend/repository/evaluation/EvaluationCustomRepository.java
  backend/src/main/java/com/dwbh/backend/repository/evaluation/EvaluationRepository.java
  backend/src/main/java/com/dwbh/backend/repository/evaluation/EvaluationRepositoryImpl.java
  backend/src/main/java/com/dwbh/backend/service/evaluation/EvaluationService.java
Labels: feat

#28 feat: 평가 crud 기능 구현
  backend/src/main/java/com/dwbh/backend/controller/evaluation/EvaluationController.java
  backend/src/main/java/com/dwbh/backend/dto/evaluation/EvaluationDTO.java
  backend/src/main/java/com/dwbh/backend/dto/evaluation/EvaluationRequest.java
  backend/src/main/java/com/dwbh/backend/entity/Evaluation.java
  backend/src/main/java/com/dwbh/backend/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/dwbh/backend/repository/evaluation/EvaluationCustomRepository.java
  backend/src/main/java/com/dwbh/backend/repository/evaluation/EvaluationRepository.java
  backend/src/main/java/com/dwbh/backend/repository/evaluation/EvaluationRepositoryImpl.java
  backend/src/main/java/com/dwbh/backend/service/evaluation/EvaluationService.java
Labels: feat

#32 Feat/#30 평가 테스트 작성
  .idea/modules.xml
  backend/src/main/java/com/dwbh/backend/controller/evaluation/EvaluationController.java
  backend/src/main/java/com/dwbh/backend/repository/evaluation/EvaluationRepositoryImpl.java
  backend/src/test/java/com/dwbh/backend/service/evaluation/EvaluationServiceTest.java
Labels: invalid

#34 Feat/notification/#26 알림조회
  backend/build.gradle
  backend/src/main/java/com/dwbh/backend/common/entity/BaseDateEntity.java
  backend/src/main/java/com/dwbh/backend/common/entity/YnType.java
  backend/src/main/java/com/dwbh/backend/config/AuditingConfig.java
  backend/src/main/java/com/dwbh/backend/config/BeanConfig.java
  backend/src/main/java/com/dwbh/backend/config/SwaggerConfig.java
  backend/src/main/java/com/dwbh/backend/controller/MainController.java
  backend/src/main/java/com/dwbh/backend/controller/chat/ChatController.java
  backend/src/main/java/com/dwbh/backend/controller/notification/NotificationController.java
  backend/src/main/java/com/dwbh/backend/dto/DTO
  backend/src/main/java/com/dwbh/backend/dto/chat/ChatDTO.java
  backend/src/main/java/com/dwbh/backend/dto/counsel_offer/CounselOfferDTO.java
  backend/src/main/java/com/dwbh/backend/dto/notification/NotificationDTO.java
  backend/src/main/java/com/dwbh/backend/dto/notification/request/CreateNotificationRequest.java
  backend/src/main/java/com/dwbh/backend/dto/user/UserDTO.java
  backend/src/main/java/com/dwbh/backend/entity/Chat.java
  backend/src/main/java/com/dwbh/backend/entity/CounselOffer.java
  backend/src/main/java/com/dwbh/backend/entity/Notification.java
  backend/src/main/java/com/dwbh/backend/entity/User.java
  backend/src/main/java/com/dwbh/backend/exception/ErrorCodeType.java
  backend/src/main/java/com/dwbh/backend/mapper/ChatMapper.java
  backend/src/main/java/com/dwbh/backend/mapper/NotificationMapper.java
  backend/src/main/java/com/dwbh/backend/repository/Repository
  backend/src/main/java/com/dwbh/backend/repository/chat/ChatRepository.java
  backend/src/main/java/com/dwbh/backend/repository/counsel_offer/CounselOfferRepository.java
  backend/src/main/java/com/dwbh/backend/repository/notification/NotificationCustomRepository.java
  backend/src/main/java/com/dwbh/backend/repository/notification/NotificationRepository.java
  backend/src/main/java/com/dwbh/backend/repository/notification/NotificationRepositoryImpl.java
  backend/src/main/java/com/dwbh/backend/repository/user/UserRepository.java
  backend/src/main/java/com/dwbh/backend/service/Service
  backend/src/main/java/com/dwbh/backend/service/chat/ChatService.java
  backend/src/main/java/com/dwbh/backend/service/notification/NotificationService.java
  backend/src/main/resources/schema.sql
  frontend/package.json
  frontend/src/components/chat/ChattingDetail.vue
  frontend/src/components/chat/ChattingList.vue
  frontend/src/router/index.js
  frontend/src/views/chat/ChatDetailView.vue
  frontend/src/views/chat/ChatListView.vue
  frontend/src/views/chat/ChatView.vue
Labels: refactor, feat

#37 refactor: dummy_data, schema.sql 수정
  backend/src/main/resources/dummy_data.sql
  backend/src/main/resources/schema.sql
Labels: refactor

#39 refactor: 평가 dto 리팩토링 후 테스트 진행
  backend/src/main/java/com/dwbh/backend/dto/evaluation/EvaluationDTO.java
  backend/src/main/java/com/dwbh/backend/dto/evaluation/EvaluationRequest.java
  backend/src/main/java/com/dwbh/backend/dto/evaluation/EvaluationResponse.java
  backend/src/main/java/com/dwbh/backend/entity/Evaluation.java
  backend/src/main/java/com/dwbh/backend/exception/ErrorCodeType.java
  backend/src/main/java/com/dwbh/backend/mapper/EvaluationMapper.java
  backend/src/main/java/com/dwbh/backend/service/evaluation/EvaluationService.java
  backend/src/test/java/com/dwbh/backend/service/evaluation/EvaluationServiceTest.java
Labels: refactor, invalid

#43 feat: 로그인, 회원가입, 시큐리티 기능 추가
  backend/build.gradle
  backend/src/main/java/com/dwbh/backend/BackendApplication.java
  backend/src/main/java/com/dwbh/backend/common/filter/CustomAuthenticationFilter.java
  backend/src/main/java/com/dwbh/backend/common/filter/JwtFilter.java
  backend/src/main/java/com/dwbh/backend/common/handler/JwtAccessDeniedHandler.java
  backend/src/main/java/com/dwbh/backend/common/handler/JwtAuthenticationEntryPoint.java
  backend/src/main/java/com/dwbh/backend/common/handler/LoginFailureHandler.java
  backend/src/main/java/com/dwbh/backend/common/handler/LoginSuccessHandler.java
  backend/src/main/java/com/dwbh/backend/common/util/JwtUtil.java
  backend/src/main/java/com/dwbh/backend/config/BeanConfig.java
  backend/src/main/java/com/dwbh/backend/config/SecurityConfig.java
  backend/src/main/java/com/dwbh/backend/config/SwaggerConfig.java
  backend/src/main/java/com/dwbh/backend/controller/UserController.java
  backend/src/main/java/com/dwbh/backend/dto/CreateUserRequest.java
  backend/src/main/java/com/dwbh/backend/dto/ExceptionResponse.java
  backend/src/main/java/com/dwbh/backend/dto/LoginRequest.java
  backend/src/main/java/com/dwbh/backend/entity/User.java
  backend/src/main/java/com/dwbh/backend/mapper/ChatMapper.java
  backend/src/main/java/com/dwbh/backend/mapper/NotificationMapper.java
  backend/src/main/java/com/dwbh/backend/repository/UserRepository.java
  backend/src/main/java/com/dwbh/backend/service/UserService.java
  backend/src/main/resources/application.yml
Labels: docs, feat

#52 Feat/#19 댓글작성
  backend/build.gradle
  backend/src/main/java/com/dwbh/backend/common/entity/Gender.java
  backend/src/main/java/com/dwbh/backend/common/util/FileUploadUtils.java
  backend/src/main/java/com/dwbh/backend/controller/offer/OfferController.java
  backend/src/main/java/com/dwbh/backend/dto/offer/CreateOfferRequest.java
  backend/src/main/java/com/dwbh/backend/dto/offer/OfferDTO.java
  backend/src/main/java/com/dwbh/backend/dto/offer/UserSummaryDTO.java
  backend/src/main/java/com/dwbh/backend/entity/CounselOffer.java
  backend/src/main/java/com/dwbh/backend/entity/CounselOfferFile.java
  backend/src/main/java/com/dwbh/backend/entity/CounselorHire.java
  backend/src/main/java/com/dwbh/backend/entity/File.java
  backend/src/main/java/com/dwbh/backend/exception/ErrorCodeType.java
  backend/src/main/java/com/dwbh/backend/repository/FileRepository.java
  backend/src/main/java/com/dwbh/backend/repository/offer/OfferInfaRepositoy.java
  backend/src/main/java/com/dwbh/backend/repository/offer/OfferRepository.java
  backend/src/main/java/com/dwbh/backend/service/offer/OfferService.java
Labels: feat

#54 feat: 게시판 crud 기능 구현
  .idea/modules.xml
  backend/src/main/java/com/dwbh/backend/controller/counselor_hire/CounselorController.java
  backend/src/main/java/com/dwbh/backend/dto/counselor_hire/CounselorDTO.java
  backend/src/main/java/com/dwbh/backend/entity/CounselorHire.java
  backend/src/main/java/com/dwbh/backend/repository/counselor_hire/CounselorRepository.java
  backend/src/main/java/com/dwbh/backend/service/counselor_hire/CounselorService.java
Labels: feat

#60 test: 채팅방 및 알림 테스트
  backend/src/main/java/com/dwbh/backend/dto/chat/ChatDTO.java
  backend/src/main/java/com/dwbh/backend/service/evaluation/EvaluationService.java
  backend/src/test/java/com/dwbh/backend/service/chat/ChatServiceTest.java
  backend/src/test/java/com/dwbh/backend/service/evaluation/EvaluationServiceTest.java
  backend/src/test/java/com/dwbh/backend/service/notification/NotificationServiceTest.java
Labels: test

#65 feat: 헤더 컴포넌트 구현
  frontend/package-lock.json
  frontend/src/components/common/ButtonSmallColor.vue
  frontend/src/components/common/Header.vue
  frontend/src/components/common/SideNotificationBar.vue
  frontend/src/images/chat.png
  frontend/src/images/notification.png
  frontend/src/router/index.js
  frontend/src/stores/auth.js
  frontend/src/views/counsel/CounselView.vue
  frontend/src/views/user/LoginView.vue
  frontend/src/views/user/MypageView.vue
  frontend/src/views/user/SignupView.vue
Labels: feat

#67 feat: 회원 조회 추가
  backend/src/main/java/com/dwbh/backend/common/util/AuthUtil.java
  backend/src/main/java/com/dwbh/backend/controller/UserController.java
  backend/src/main/java/com/dwbh/backend/dto/UserDetailResponse.java
  backend/src/main/java/com/dwbh/backend/dto/user/UserModifyResponse.java
  backend/src/main/java/com/dwbh/backend/entity/User.java
  backend/src/main/java/com/dwbh/backend/entity/UserProfileFile.java
  backend/src/main/java/com/dwbh/backend/mapper/ChatMapper.java
  backend/src/main/java/com/dwbh/backend/mapper/NotificationMapper.java
  backend/src/main/java/com/dwbh/backend/repository/user/CustomUserRepository.java
  backend/src/main/java/com/dwbh/backend/repository/user/UserRepository.java
  backend/src/main/java/com/dwbh/backend/service/UserService.java
  backend/src/main/java/com/dwbh/backend/service/counselor_hire/CounselorService.java
Labels: feat

#68 Feat/#53 댓글수정
  backend/src/main/java/com/dwbh/backend/common/entity/Gender.java
  backend/src/main/java/com/dwbh/backend/common/util/FileUploadUtils.java
  backend/src/main/java/com/dwbh/backend/controller/offer/OfferController.java
  backend/src/main/java/com/dwbh/backend/dto/offer/CreateOrUpdateOfferRequest.java
  backend/src/main/java/com/dwbh/backend/dto/offer/OfferDTO.java
  backend/src/main/java/com/dwbh/backend/entity/CounselOffer.java
  backend/src/main/java/com/dwbh/backend/entity/CounselorHire.java
  backend/src/main/java/com/dwbh/backend/entity/File.java
  backend/src/main/java/com/dwbh/backend/exception/ErrorCodeType.java
  backend/src/main/java/com/dwbh/backend/repository/FileRepository.java
  backend/src/main/java/com/dwbh/backend/repository/file/FileRepository.java
  backend/src/main/java/com/dwbh/backend/repository/offer/OfferRepository.java
  backend/src/main/java/com/dwbh/backend/service/offer/OfferService.java
  backend/src/main/resources/dummy_data.sql
Labels: refactor, feat

#75 Feat/#70 댓글조회 및 crud 리팩토링
  backend/src/main/java/com/dwbh/backend/controller/counsel_offer/OfferController.java
  backend/src/main/java/com/dwbh/backend/dto/counsel_offer/CreateOrUpdateOfferRequest.java
  backend/src/main/java/com/dwbh/backend/dto/counsel_offer/OfferResponse.java
  backend/src/main/java/com/dwbh/backend/dto/offer/OfferDTO.java
  backend/src/main/java/com/dwbh/backend/dto/offer/UserSummaryDTO.java
  backend/src/main/java/com/dwbh/backend/exception/ErrorCodeType.java
  backend/src/main/java/com/dwbh/backend/repository/counsel_offer/CounselOfferRepository.java
  backend/src/main/java/com/dwbh/backend/repository/counsel_offer/OfferCustomRepository.java
  backend/src/main/java/com/dwbh/backend/repository/counsel_offer/OfferCustomRepositoryImpl.java
  backend/src/main/java/com/dwbh/backend/repository/offer/OfferInfaRepositoy.java
  backend/src/main/java/com/dwbh/backend/repository/offer/OfferRepository.java
  backend/src/main/java/com/dwbh/backend/service/counsel_offer/OfferService.java
  backend/src/main/resources/dummy_data.sql
Labels: refactor, enhancement, feat

#77 feat: 중복 여부 체크 API 추가
  backend/src/main/java/com/dwbh/backend/controller/UserController.java
  backend/src/main/java/com/dwbh/backend/entity/User.java
  backend/src/main/java/com/dwbh/backend/repository/user/UserRepository.java
  backend/src/main/java/com/dwbh/backend/service/UserService.java
Labels: feat

#79 refactor: 각종 중복 체크
  backend/src/main/java/com/dwbh/backend/controller/UserController.java
  backend/src/main/java/com/dwbh/backend/dto/CreateUserRequest.java
  backend/src/main/java/com/dwbh/backend/dto/user/ModifyUserRequest.java
  backend/src/main/java/com/dwbh/backend/exception/ErrorCodeType.java
  backend/src/main/java/com/dwbh/backend/service/UserService.java
Labels: refactor

#80 feat: 회원 탈퇴 기능 추가
  backend/src/main/java/com/dwbh/backend/controller/UserController.java
  backend/src/main/java/com/dwbh/backend/entity/User.java
  backend/src/main/java/com/dwbh/backend/service/UserService.java
Labels: feat

#84 test: 유저 서비스 테스트 코드 작성
  backend/src/main/java/com/dwbh/backend/dto/CreateUserRequest.java
  backend/src/main/java/com/dwbh/backend/dto/user/ModifyUserRequest.java
  backend/src/main/resources/dummy_data.sql
  backend/src/test/java/com/dwbh/backend/service/UserServiceTest.java
Labels: test

#91 feat: 평가 화면 구현
  .idea/modules.xml
  backend/src/main/java/com/dwbh/backend/controller/evaluation/EvaluationController.java
  backend/src/main/java/com/dwbh/backend/dto/evaluation/EvaluationCommentResponse.java
  backend/src/main/java/com/dwbh/backend/dto/evaluation/EvaluationResponse.java
  backend/src/main/java/com/dwbh/backend/mapper/EvaluationMapper.java
  backend/src/main/java/com/dwbh/backend/service/evaluation/EvaluationService.java
  frontend/index.html
  frontend/src/components/chat/ChattingList.vue
  frontend/src/components/common/Header.vue
  frontend/src/components/common/InputBoxLong.vue
  frontend/src/components/common/ModalSmall.vue
  frontend/src/components/user/RegisterForm.vue
  frontend/src/images/favicon.ico
  frontend/src/images/ms-icon-310x310.png
  frontend/src/router/index.js
  frontend/src/stores/auth.js
  frontend/src/util/evaluationApi.js
  frontend/src/views/evaluation/EvaluationView.vue
  frontend/src/views/user/RegisterView.vue
  frontend/src/views/user/SignupView.vue
Labels: refactor, feat

#92 Feat/#78 게시글 상세조회
  backend/src/main/java/com/dwbh/backend/controller/counsel_offer/OfferController.java
  backend/src/main/java/com/dwbh/backend/controller/counselor_hire/CounselorController.java
  backend/src/main/java/com/dwbh/backend/dto/counselor_hire/CounselorDTO.java
  backend/src/main/java/com/dwbh/backend/dto/counselor_hire/CounselorDetailResponse.java
  backend/src/main/java/com/dwbh/backend/entity/CounselorAge.java
  backend/src/main/java/com/dwbh/backend/entity/CounselorHire.java
  backend/src/main/java/com/dwbh/backend/entity/CounselorHireFile.java
  backend/src/main/java/com/dwbh/backend/entity/CounselorHireType.java
  backend/src/main/java/com/dwbh/backend/entity/CounselorType.java
  backend/src/main/java/com/dwbh/backend/exception/ErrorCodeType.java
  backend/src/main/java/com/dwbh/backend/repository/counsel_offer/OfferCustomRepository.java
  backend/src/main/java/com/dwbh/backend/repository/counsel_offer/OfferCustomRepositoryImpl.java
  backend/src/main/java/com/dwbh/backend/repository/counselor_hire/CounselorAgeRepository.java
  backend/src/main/java/com/dwbh/backend/repository/counselor_hire/CounselorCustomRepository.java
  backend/src/main/java/com/dwbh/backend/repository/counselor_hire/CounselorCustomRepositoryImpl.java
  backend/src/main/java/com/dwbh/backend/repository/counselor_hire/CounselorRepository.java
  backend/src/main/java/com/dwbh/backend/repository/counselor_hire/CounselorTypeRepository.java
  backend/src/main/java/com/dwbh/backend/service/counsel_offer/OfferService.java
  backend/src/main/java/com/dwbh/backend/service/counselor_hire/CounselorService.java
Labels: refactor, feat

#101 feat: 이메일 인증 기능 추가
  backend/build.gradle
  backend/src/main/java/com/dwbh/backend/BackendApplication.java
  backend/src/main/java/com/dwbh/backend/common/util/JwtUtil.java
  backend/src/main/java/com/dwbh/backend/common/util/RandomStringGeneratorUtil.java
  backend/src/main/java/com/dwbh/backend/config/SwaggerConfig.java
  backend/src/main/java/com/dwbh/backend/controller/UserController.java
  backend/src/main/java/com/dwbh/backend/dto/user/SendEmailRequest.java
  backend/src/main/java/com/dwbh/backend/exception/ErrorCodeType.java
  backend/src/main/java/com/dwbh/backend/service/EmailService.java
  backend/src/main/java/com/dwbh/backend/service/UserService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/dwbh/backend/service/UserServiceTest.java
Labels: refactor, feat

#99 refactor: 평가 접근 권한 체킹 구현
  backend/src/main/java/com/dwbh/backend/common/util/AuthUtil.java
  backend/src/main/java/com/dwbh/backend/controller/evaluation/EvaluationController.java
  backend/src/main/java/com/dwbh/backend/service/evaluation/EvaluationService.java
  backend/src/test/java/com/dwbh/backend/service/evaluation/EvaluationServiceTest.java
  frontend/src/stores/auth.js
  frontend/src/util/evaluationApi.js
  frontend/src/views/evaluation/EvaluationView.vue
Labels: refactor, feat, test

#104 feat: 초기 도커 파일 작성
  backend/Dockerfile
  frontend/Dockerfile
Labels: feat

#106 Feat/counsel create#105
  .idea/modules.xml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/Pagination.vue
  frontend/src/css/style.css
  frontend/src/router/index.js
  frontend/src/views/counsel/CounselCreateView.vue
  frontend/src/views/counsel/CounselListView.vue
Labels: feat

#116 feat: 알림 화면 구현
  backend/src/main/java/com/dwbh/backend/controller/notification/NotificationController.java
  backend/src/main/java/com/dwbh/backend/dto/notification/NotificationDTO.java
  backend/src/main/java/com/dwbh/backend/dto/notification/NotificationResponse.java
  backend/src/main/java/com/dwbh/backend/entity/Notification.java
  backend/src/main/java/com/dwbh/backend/service/notification/NotificationService.java
  backend/src/test/java/com/dwbh/backend/service/notification/NotificationServiceTest.java
  frontend/src/components/common/Header.vue
  frontend/src/components/common/SideNotificationBar.vue
  frontend/src/components/notification/NotificationForm.vue
  frontend/src/stores/auth.js
Labels: feat, test

#119 feat: 로그인 회원가입 기능 구현
  .idea/modules.xml
  backend/src/main/java/com/dwbh/backend/config/SecurityConfig.java
  backend/src/main/java/com/dwbh/backend/dto/CreateUserRequest.java
  frontend/src/components/common/Header.vue
  frontend/src/components/common/SideNotificationBar.vue
  frontend/src/components/user/LoginForm.vue
  frontend/src/components/user/RegisterForm.vue
  frontend/src/stores/auth.js
  frontend/src/views/evaluation/EvaluationView.vue
  frontend/src/views/user/LoginView.vue
  frontend/src/views/user/RegisterView.vue
Labels: refactor, feat, test

#120 fix: dockerfile 수정
  frontend/Dockerfile
  frontend/nginx.conf
Labels: refactor

#124 fix: 유저 상세 조회에서 파일 정보가 없는 유저가 검색되지 않는 문제 left join으로 해결
  backend/src/main/java/com/dwbh/backend/repository/user/CustomUserRepository.java
Labels: bug

#126 refactor: 컨테이너 자동 재시작 설정 추가
  docker-compose.yml
Labels: refactor

#129 refactor: 전체리팩토링
  frontend/src/components/common/Header.vue
  frontend/src/components/common/SideNotificationBar.vue
  frontend/src/components/user/RegisterForm.vue
  frontend/src/views/evaluation/EvaluationView.vue
  frontend/src/views/user/LoginView.vue
Labels: refactor

#132 bug: 헤더수정
  frontend/src/components/common/Header.vue
Labels: bug

#139 fix: 쿠버네티스 대응 env 파일 optional 위치 추가
  backend/src/main/resources/application.yml
Labels: refactor

#136 feat: 마이페이지 화면 구현
  backend/src/main/java/com/dwbh/backend/service/evaluation/EvaluationService.java
  frontend/src/components/common/Header.vue
  frontend/src/components/user/UserInfo.vue
  frontend/src/router/index.js
  frontend/src/views/user/LoginView.vue
  frontend/src/views/user/MypageView.vue
Labels: feat, test

#146 docs: readme 기본 작성
  README.md
Labels: docs

#157 feat:게시글
  backend/src/main/java/com/dwbh/backend/controller/counselor_hire/CounselorController.java
  backend/src/main/java/com/dwbh/backend/dto/counselor_hire/CounselorAgeDTO.java
  backend/src/main/java/com/dwbh/backend/dto/counselor_hire/CreateCounselorRequest.java
  backend/src/main/java/com/dwbh/backend/dto/counselor_hire/CreateCounselorViewResponse.java
  backend/src/main/java/com/dwbh/backend/entity/CounselorHire.java
  backend/src/main/java/com/dwbh/backend/entity/CounselorHireAge.java
  backend/src/main/java/com/dwbh/backend/entity/CounselorHireFile.java
  backend/src/main/java/com/dwbh/backend/entity/CounselorHireType.java
  backend/src/main/java/com/dwbh/backend/repository/counselor_hire/CounselorRepositoryImpl.java
  backend/src/main/java/com/dwbh/backend/service/counselor_hire/CounselorService.java
  frontend/src/views/counsel/CounselCreateView.vue
  frontend/src/views/counsel/CounselDetailView.vue
Labels: feat

#165 bug: 알림 채팅방 연결 문제 해결
  backend/src/main/java/com/dwbh/backend/controller/notification/NotificationController.java
  backend/src/main/java/com/dwbh/backend/dto/chat/ChatDTO.java
  frontend/src/components/notification/NotificationForm.vue
Labels: bug

#163 bug: 더미데이터 추가 및 오타 수정
  backend/src/main/resources/dummy_data.sql
  frontend/src/components/user/RegisterForm.vue
Labels: bug

#170 docs: readme 수정
  README.md
Labels: docs
